// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPrxuO0J2zcE1j8N-abV-NVexbnyFeAto',
    appId: '1:212623327065:web:abe65859750a02f1d1d648',
    messagingSenderId: '212623327065',
    projectId: 'fooddeliveryapp-62e8a',
    authDomain: 'fooddeliveryapp-62e8a.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-62e8a.appspot.com',
    measurementId: 'G-SE88RJNLNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCs8_BPc7bqa_332YksGaVYHO0lwquzJg',
    appId: '1:212623327065:android:025cf0087423aaced1d648',
    messagingSenderId: '212623327065',
    projectId: 'fooddeliveryapp-62e8a',
    storageBucket: 'fooddeliveryapp-62e8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVp52pBcZZkeS7iPcO382a5QU8XnFx8mY',
    appId: '1:212623327065:ios:c48ce7ea5f3ee3d6d1d648',
    messagingSenderId: '212623327065',
    projectId: 'fooddeliveryapp-62e8a',
    storageBucket: 'fooddeliveryapp-62e8a.appspot.com',
    iosClientId: '212623327065-ev4u92n1fv1e3nj6kqj7na12r5vqlgfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.deeplinking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVp52pBcZZkeS7iPcO382a5QU8XnFx8mY',
    appId: '1:212623327065:ios:377b1e3ca3fd8b48d1d648',
    messagingSenderId: '212623327065',
    projectId: 'fooddeliveryapp-62e8a',
    storageBucket: 'fooddeliveryapp-62e8a.appspot.com',
    iosClientId: '212623327065-2ki2djamtv5394bsfkedof6hv2khu0r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.deeplinking.RunnerTests',
  );
}
